services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-webgestao
    environment:
      MYSQL_DATABASE: webgestao
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3307:3306"  # <- Porta externa 3307, para não conflitar se houver outro MySQL
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
  
